### ISSUE TITLE
gen_release_notes containers version

### ISSUE THREAD

**Issue by brooksn** [rancher/ecm-distro-tools#220] opened 2023-06-30 20:44 UTC
Containerd version was set to v0.0.0 for v1.26.6+k3s1 and for v1.27.3+k3s1 after running gen_release_notes

**Comment by Tashima42** [comment] 2023-07-04 19:41
Hey @brooksn, what arguments did you use? I couldn't reproduce this issue.
 
```
gen_release_notes -p v1.26.5+k3s1 -m v1.26.6+k3s1 -r k3s
```

**Comment by Tashima42** [comment] 2023-07-07 16:40
This issue was caused by an incorrect usage of the build script to check the containerd version, instead of the go mod. The incorrect file was used due to an insufficient version check used in the release note template for k3s: https://github.com/rancher/ecm-distro-tools/blob/7330dced76c86f3510c200f4fab2fdcb214c664d/release/release.go#L545-L551

This is already fixed in the latest version:
https://github.com/rancher/ecm-distro-tools/blob/77c9043241babf6b58f428344125ebdd7ea2f6c8/release/release.go#L595-L599

Brooks sent me the following command to reproduce the error:
```
docker run --rm rancher/ecm-distro-tools@sha256:3c141a7c2c838076a0d34f77fcfa59db926f3e6f1b89fa8e164b2f3f03a5e032 gen_release_notes -p v1.26.5+k3s1 -m v1.26.6-rc1+k3s1 -r k3s
```
The version used in this docker image was the following:
```
time="2023-07-07T13:20:52Z" level=info msg="version: v0.4.0 - git sha: 7330dced76c86f3510c200f4fab2fdcb214c664d\n"
```

**Closed by Tashima42** 2023-07-07 16:40 UTC
